"""add workflow task definitions

Revision ID: 4f5ead2f930f
Revises: 2bc50e5e2606
Create Date: 2026-08-16 13:03:26.563387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f5ead2f930f'
down_revision: Union[str, Sequence[str], None] = '2bc50e5e2606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_task_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_definition_id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_role', sa.String(length=50), nullable=True),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_task_definitions_id'), 'workflow_task_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_task_definitions_workflow_definition_id'), 'workflow_task_definitions', ['workflow_definition_id'], unique=False)
    op.add_column('workflow_definitions', sa.Column('department', sa.String(length=100), nullable=False))
    op.add_column('workflow_definitions', sa.Column('job_title', sa.String(length=100), nullable=False))
    op.add_column('workflow_definitions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_workflow_definitions_job_title'), 'workflow_definitions', ['job_title'], unique=False)
    op.create_index(op.f('ix_workflow_runs_employee_id'), 'workflow_runs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_definition_id'), 'workflow_runs', ['workflow_definition_id'], unique=False)
    op.add_column('workflow_tasks', sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_workflow_tasks_workflow_run_id'), 'workflow_tasks', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tasks_workflow_run_id'), table_name='workflow_tasks')
    op.drop_column('workflow_tasks', 'depends_on')
    op.drop_index(op.f('ix_workflow_runs_workflow_definition_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_employee_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_definitions_job_title'), table_name='workflow_definitions')
    op.drop_column('workflow_definitions', 'updated_at')
    op.drop_column('workflow_definitions', 'job_title')
    op.drop_column('workflow_definitions', 'department')
    op.drop_index(op.f('ix_workflow_task_definitions_workflow_definition_id'), table_name='workflow_task_definitions')
    op.drop_index(op.f('ix_workflow_task_definitions_id'), table_name='workflow_task_definitions')
    op.drop_table('workflow_task_definitions')
    # ### end Alembic commands ###
